# Generated by Django 5.2.3 on 2025-07-12 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='模组名称')),
                ('description', models.TextField(verbose_name='模组描述')),
                ('author', models.CharField(max_length=255, verbose_name='模组作者')),
                ('tags', models.JSONField(default=list, help_text='字段格式：[ str, str , ... ]', verbose_name='模组标签')),
                ('version', models.CharField(max_length=255, null=True, verbose_name='模组版本')),
                ('url', models.URLField(null=True, verbose_name='模组下载链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='ModItemInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FilePathField(null=True, verbose_name='图片路径')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='物品名称')),
                ('description', models.CharField(max_length=1000, verbose_name='物品描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('belonging_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_item_info', to='app.modinfo', verbose_name='所属模组')),
            ],
        ),
    ]
