# Generated by Django 5.2.3 on 2025-07-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorFeedbackInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('error_scenario', models.CharField(verbose_name='错误场景')),
                ('contact', models.CharField(verbose_name='联系方式')),
                ('filepaths', models.JSONField(verbose_name='附件路径')),
            ],
        ),
    ]
