# Generated by Django 5.2.3 on 2025-07-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_errorfeedbackinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=260, verbose_name='文件名')),
                ('filetype', models.CharField(max_length=100, null=True, verbose_name='文件类型')),
                ('filesize', models.IntegerField(verbose_name='文件大小')),
                ('file_content', models.BinaryField(verbose_name='文件内容')),
            ],
        ),
    ]
