# Generated by Django 5.2.3 on 2025-07-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_filestorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='is_temporary',
            field=models.BooleanField(default=True, verbose_name='是否是临时文件'),
        ),
    ]
