"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# 项目根目录
ROOT_DIR = BASE_DIR.parent
# 源代码所在目录
SOURCE_DIR = BASE_DIR
# 资源文件所在目录
RESOURCES_DIR = ROOT_DIR / "resources"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ok))2mb#mev0$i$9i9-c9130*r26iveph$$=-927l(uwp9i4(k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
CUSTOM_DEBUG = DEBUG and True

ALLOWED_HOSTS = []

# Application definition

# 告诉 Django 项目中包含哪些应用，激活应用的各项功能（模型、视图、模板等）
# 使 Django 能够识别应用的数据库模型，允许通过 makemigrations 和 migrate 管理数据库迁移
# 加载每个应用的 apps.py 中的 AppConfig 类，执行应用的初始化代码（在 AppConfig.ready() 方法中）
# 自动发现应用的 admin.py 文件，将模型注册到 Django 管理后台
INSTALLED_APPS = [
    # 管理界面、用户认证系统内容类型框架（通用关系）、会话管理、一次性消息框架、静态文件管理
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 用于开发 RESTful API
    "rest_framework",
    # DRF 自带的 Token 认证
    "rest_framework.authtoken",

    "rest_framework_simplejwt",
    "ninja_extra",

    "django_extensions",

    "apps.testdjangoapi",
    "apps.testdrfapi",
    "apps.ninjaapi",
    "apps.powernetwork",
    "apps.powernetworkreport",
    "apps.account",
]

# drf 配置字典
REST_FRAMEWORK = {
    # 自带分页类
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 每页数据量
    'PAGE_SIZE': 50,
    # 时间显示格式
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    # 返回response对象所用的类
    'DEFAULT_RENDER_CLASSES': [
        'rest_framework.renders.JSONRenderer',
        'rest_framework.renders.BrowsableAPIRenderer',
    ],
    # 解析器，如何解析request请求中的request.data
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    # 权限相关配置：必须登录才能调用接口
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        # Use Django's standard `django.contrib.auth` permissions,
        # or allow read-only access for unauthenticated users.
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    # 认证相关配置
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        # [command] python manage.py drf_create_token {username} 可以手动生成 Token
        'rest_framework.authentication.TokenAuthentication',
    ],
    # todo: [to be understood] URL_FIELD_NAME
    # "URL_FIELD_NAME": 'link',
    # DRF 接口文档生成
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 设置国际化中间件
    "django.middleware.locale.LocaleMiddleware",
]


# todo: 创建 logs 文件夹
def _create_logs_directory():
    logs_directory = ROOT_DIR / "logs"
    if logs_directory.exists():
        return
    logs_directory.mkdir()


_create_logs_directory()

# django 内置完整的日志记录框架
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '''
            asctime: %(asctime)s
            levelname: %(levelname)s
            message: %(message)s
            module: %(module)s
            pathname: %(pathname)s
            exc_info: %(exc_info)s
            process: %(process)d
            thread: %(thread)d
        '''
        }
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            # 目录不会自动创建
            'filename': 'logs/django_errors.log',
            # 5 MB
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        'json_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/django_errors.json',
            # 5 MB
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'json',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'mail_admins', 'json_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file', 'mail_admins', 'json_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'myapp': {
            'handlers': ['console', 'file', 'json_file'],
            'level': 'DEBUG',
        },
        'critical': {
            'handlers': ['mail_admins'],
            'level': 'CRITICAL',
        }
    }
}

# todo: [to be sloved] 因为 RESTframework 是有前端文件的，后面使用时会全部放到这个目录
# STATIC_ROOT = BASE_DIR / "static"

# 静态文件配置
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# 配置登录重定向
LOGIN_REDIRECT_URL = 'testdrfapi/test/test'
LOGOUT_REDIRECT_URL = 'api-auth/login/'

ROOT_URLCONF = 'backend.urls'

# 模板配置
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
