# Generated by Django 5.2.3 on 2025-07-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usermodel_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='app_user',
        ),
    ]
