# Generated by Django 5.2.3 on 2025-07-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usermodel_options_alter_usermodel_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
